sigoden/aichat

Cargo.lock, Cargo.toml, src/render.rs, src/repl.rs
We also show question at the begining
=> refactor: use tui for better stream render

Cargo.lock, Cargo.toml, src/editor.rs, src/main.rs, src/render.rs, src/repl.rs
Use `.editor` to edit/input multiline text
=> feat: add `.editor` command

src/repl.rs
.clear => .clear screen
.clear-history => .clear history
.clear-role => .clear role
=> refactor: adjusted command name

Cargo.lock, Cargo.toml, README.md, src/main.rs
=> feat: accept pipe

Cargo.lock, Cargo.toml, src/config.rs, src/main.rs, src/repl/handler.rs, src/repl/mod.rs, src/utils.rs
- abandon .copy
- rename .multiple => .editor
- if command successed, do not output `Done`
- if command failed, output `Error: <error message>`
=> refactor: adjust repl

src/render/mod.rs, src/render/repl.rs
=> fix: windows no stream output

src/main.rs, src/render/mod.rs, src/render/repl.rs, src/repl/handler.rs
command mode: should no extra newline
chat mode: should have one newline
=> chore: optimize newline again

src/repl/init.rs, src/repl/mod.rs
=> feat: add role info to readline indicator

src/client.rs, src/config/conversation.rs, src/config/mod.rs, src/repl/handler.rs, src/repl/init.rs, src/repl/mod.rs
```
〉.conversation
＄.clear conversation
〉
```
close #40
=> feat: support conversation

src/config/conversation.rs, src/config/mod.rs
If set true, start a conversation immediately upon repl.
=> feat: add config.conversation_first

src/config/mod.rs, src/main.rs
=> fix: cli specify role is not applied when conversation_first set true

src/client.rs, src/config/mod.rs
- AICHAT_CONFIG_DIR: sepecify the configuration directory
- AICHAT_ROLES_FILE: set the `roles.yaml` file path
- AICHAT_API_KEY: set the api key
=> feat: support more env vars

src/cli.rs, src/main.rs
use `aichat --info` to print information
=> feat: add `--info`

Cargo.lock, Cargo.toml, src/repl/init.rs, src/repl/mod.rs
=> feat: support backeted paste

src/config/mod.rs
=> fix: config file with strict perms

src/config/mod.rs, src/repl/init.rs
close #140
add `vi_keybindings: true` to enable it
=> feat: suppport vi keybindings

src/repl/mod.rs
=> fix: parse command fails if command following newline

src/repl/handler.rs, src/utils/mod.rs
=> fix: .copy don't works on some linux distro

src/config/mod.rs, src/config/session.rs, src/main.rs, src/repl/handler.rs, src/repl/mod.rs
=> fix: bugs between sesison/role

README.md, src/config/mod.rs
This will help to use aichat in scripts
=> feat: force nowrap if no tty/terminal

Cargo.toml, README.md, src/client/azure_openai.rs, src/client/localai.rs, src/client/openai.rs, src/config/message.rs, src/config/mod.rs, src/config/model_info.rs, src/config/session.rs, src/main.rs, src/render/repl.rs, src/repl/prompt.rs
- extends ModelInfo for tokens calculating
- refactor config/session.rs, improve export, render, getter/setter
- modify main.rs, allow --model override session.model
=> refactor: improve code quanity

README.md, src/config/mod.rs, src/repl/mod.rs
```
〉""" .role emoji
hello world
"""
👋🌍
〉
```
=> feat: temporarily use a role to send a message

src/config/mod.rs, src/render/repl.rs
=> fix: unexpected additional newline in REPL

README.md, src/repl/completer.rs, src/repl/mod.rs
=> refactor: use ::: as multipline input indicator, deprecate """

src/render/stream.rs
=> feat: add a spinner to indicate waiting for response

src/config/mod.rs, src/repl/completer.rs
- sort sessions
- nosort models
- nosort roles
=> refactor: sort of some complete type

Cargo.lock, Cargo.toml
=> fix: pipe failed on macos

src/config/mod.rs
=> chore: update change session error message

src/config/input.rs
=> fix: cannot read image with uppercase ext

README.md, config.example.yaml, src/client/common.rs, src/client/ernie.rs, src/client/gemini.rs, src/client/mod.rs, src/client/palm.rs, src/utils/mod.rs
```yaml
clients:
- type: gemini
api_key: AIxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```
close #271
=> feat: support gemini

README.md, config.example.yaml, src/client/mod.rs, src/client/ollama.rs
```yaml
clients:
- type: ollama
api_base: http://localhost:11434/api
models:
- name: codellama
- name: llava
```
close #241
=> feat: support ollama

Cargo.lock, Cargo.toml
=> fix: copy on linux wayland

Cargo.lock, Cargo.toml, config.example.yaml, src/client/azure_openai.rs, src/client/common.rs, src/client/ernie.rs, src/client/gemini.rs, src/client/localai.rs, src/client/model.rs, src/client/ollama.rs, src/client/openai.rs, src/client/qianwen.rs, src/config/input.rs, src/main.rs, src/repl/mod.rs
1. automatically switch to the model that has the necessary capabilities.
2. throw an error if the client does not have a model with the necessary capabilities
=> feat: supports model capabilities

src/client/gemini.rs, src/client/openai.rs, src/client/qianwen.rs
=> feat: update openai/qianwen/gemini models

README.md, src/cli.rs, src/config/mod.rs, src/config/role.rs, src/main.rs, src/utils/mod.rs
Simply input what you want to do in natural language, and aichat will prompt and run the command that achieves your intent.
```
aichat -s <text>...
```
close #312 #120
=> feat: support `-e/--execute` to execute shell command

README.md, config.example.yaml, src/client/claude.rs, src/client/mod.rs
```yaml
clients:
- type: claude
api_key: xxx
```
=> feat: support claude

README.md, src/config/mod.rs, src/config/session.rs, src/repl/mod.rs
=> feat: add `.clear messages` to clear session messages

src/client/claude.rs
=> feat: support claude-3

src/client/ernie.rs
new models:
- ernie:ernie-3.5-4k-0205
- ernie:ernie-3.5-8k-0205
- ernie:ernie-speed
=> feat: add new ernie models

src/config/mod.rs, src/repl/mod.rs
=> fix: erratic behaviour when using  temp role in a session

src/client/message.rs, src/config/input.rs, src/config/mod.rs, src/main.rs, src/repl/mod.rs
=> feat: allow use of temporary role in a session

src/config/mod.rs, src/config/session.rs
This also fix the missing `.exit role` completion after `.clear messages`.
=> refactor: remove role field from session struct

src/client/ernie.rs
New models:
- ernie-speed-128k
- ernie-lite-8k
Rename models:
- ernie-bot-4  -> ernie-4.0-8k
- ernie-3.5-4k-0205 -> ernie-3.5-4k
- ernie-3.5-8k-0205 -> ernie-3.5-8k
- ernie-speed -> ernie-speed-8k
Remove models:
- ernie-bot-8k
- ernie-bot
- ernie-bot-turbo
=> feat: update ernie models

src/config/mod.rs, src/render/markdown.rs
=> fix: color on non-truecolor terminal

src/client/vertexai.rs
=> fix: vertexai model names

README.md, config.example.yaml, src/client/claude.rs, src/client/ernie.rs, src/client/openai.rs, src/client/qianwen.rs, src/config/mod.rs, src/config/role.rs
Different LLM/platforms have different temperature value ranges.
Openai/Qianwen: (0, 2.0]
Claude/Mistral/Ernie: (0, 1.0]
others: unknown or variant
Automatically convert temperature value is not practical,
=> refactor: do not automatically convert temperature value

README.md, config.example.yaml, src/client/mod.rs, src/client/moonshot.rs
```
clients:
- type: moonshot
api_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```
=> feat: support moonshot

src/client/claude.rs, src/client/gemini.rs, src/client/mistral.rs, src/client/openai.rs, src/client/qianwen.rs, src/client/vertexai.rs
=> refactor: reorder models

README.md, config.example.yaml, src/client/mod.rs, src/client/openai_compatible.rs
BREAKING CHANGE: rename client localai to openai-compatible
=> feat: rename client localai to openai-compatible

README.md, config.example.yaml, src/cli.rs, src/config/mod.rs, src/config/session.rs, src/main.rs
```
save_session: null # Whether to save the session, if null, asking
```
=> feat: `save_session` config item can be null

README.md, src/config/mod.rs, src/config/session.rs, src/repl/mod.rs
use `.save session` to save session to file manually.
related to #371
=> feat: add repl command `.save session`

src/render/stream.rs
=> fix: incorrectly render text contains tabs

src/client/vertexai.rs
Adjust error message when request blocked by safety settings
```
Failed to get answer
Caused by:
Blocked by safety settings，consider ajusting `block_threshold` in the client configuraion
```
=> refactor: gemini/vertexai blocked by safety

src/client/gemini.rs, src/client/vertexai.rs
```
gemini:gemini-1.0-pro-latest
gemini:gemini-1.0-pro-vision-latest
gemini:gemini-1.5-pro-latest
vertexai:gemini-1.0-pro
vertexai:gemini-1.0-pro-vision
vertexai:gemini-1.5-pro-preview-0409
```
=> refactor: update gemini/vertexai models list

scripts/completions/aichat.bash, scripts/completions/aichat.fish, scripts/completions/aichat.nu, scripts/completions/aichat.ps1, scripts/completions/aichat.zsh
=> feat: add completion scripts

src/config/mod.rs, src/config/role.rs, src/main.rs
* rename
```
__execute__=> %shell%
__describe_command__ => %explain%
__code__ => %code%
```
* selectable 
```
aichat -r %shell% install vim
```
=> feat:  make built-in roles selectable and rename them

src/config/input.rs, src/main.rs
```
$ aichat -e list ts files
ls *.ts
> [1]:execute [2]:explain [3]:revise [4]:exit 3
> Enter your revision: use find
find . -name "*.ts" -type f
> [1]:execute [2]:explain [3]:revise [4]:exit 3
> Enter your revision: exclude node_modules
find . -name "*.ts" -type f ! -path "./node_modules/*"
```
=> feat: shell commands support revision

config.example.yaml, src/config/mod.rs, src/main.rs, src/repl/mod.rs
```yaml
buffer_editor: null
```
=> feat: add config `buffer_editor`

src/config/mod.rs, src/config/role.rs, src/repl/mod.rs
Use system prompt through temporary role
```
.prompt                  Use a temp role with this prompt
```
```
> .prompt
Usage: .prompt <text>...
%%> .prompt to emoji
%%> hello world
👋🌎
```
=> feat: add `.prompt` repl command

src/main.rs, src/render/stream.rs, src/utils/mod.rs, src/utils/spinner.rs
https://github.com/sigoden/aichat/assets/4012553/86b92c95-3296-436d-980f-46986d04cf99
=> refactor: shell execution with spinner and select prompt

src/main.rs, src/repl/mod.rs, src/utils/mod.rs, src/utils/spinner.rs
=> refactor: tell user session compression

config.example.yaml, src/client/groq.rs, src/client/mod.rs
```
clients:
- type: groq
api_key: gsk_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```
```
groq:llama3-8b-8192
groq:llama3-70b-8192
groq:llama2-70b-4096
groq:mixtral-8x7b-32768
groq:gemma-7b-it
```
close #422
=> feat: support groq

config.example.yaml, src/client/mod.rs, src/client/moonshot.rs
=> feat: support moonshot again

config.example.yaml, src/client/mod.rs, src/client/perplexity.rs
```yaml
clients:
- type: perplexity
api_key: pplx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```
```
perplexity:sonar-small-chat
perplexity:sonar-small-online
perplexity:sonar-medium-chat
perplexity:sonar-medium-online
perplexity:llama-3-8b-instruct
perplexity:llama-3-70b-instruct
perplexity:codellama-70b-instruct
perplexity:mistral-7b-instruct
perplexity:mixtral-8x7b-instruct
perplexity:mixtral-8x22b-instruct
```
=> feat: support perplexity

scripts/completions/aichat.bash, scripts/completions/aichat.fish, scripts/completions/aichat.nu, scripts/completions/aichat.ps1, scripts/completions/aichat.zsh, src/cli.rs, src/main.rs, src/repl/mod.rs
`--prompt` option will set the system message, it create a temporary role internally.
```sh
aichat --prompt 'act as js console` Date.now()
```
=> feat: add `--prompt` option

Argcfile.sh, models.yaml, src/client/bedrock.rs, src/client/claude.rs, src/client/cohere.rs, src/client/common.rs, src/client/ernie.rs, src/client/ollama.rs, src/client/openai.rs, src/client/qianwen.rs, src/client/vertexai.rs, src/main.rs, src/repl/mod.rs, src/serve.rs
non-streaming returns CompletionStats
```
pub struct CompletionStats {
pub id: Option<String>,
pub input_tokens: Option<u64>,
pub output_tokens: Option<u64>,
}
```
It can be used to print token usage and costs later.
=> feat: non-streaming returns completion stats

src/client/common.rs, src/client/mod.rs
Add clients:
- anyscale
- deepinfra
- fireworks
- octoai
- together
=> feat: support more openai compatiable clients

src/client/common.rs, src/client/model.rs, src/config/mod.rs, src/serve.rs
```
.set max_output_tokens 4096
```
=> feat: add repl command `.set max_output_tokens`

Argcfile.sh, config.example.yaml, models.yaml, src/client/azure_openai.rs, src/client/bedrock.rs, src/client/claude.rs, src/client/cloudflare.rs, src/client/cohere.rs, src/client/common.rs, src/client/ernie.rs, src/client/gemini.rs, src/client/groq.rs, src/client/mistral.rs, src/client/mod.rs, src/client/model.rs, src/client/moonshot.rs, src/client/ollama.rs, src/client/openai.rs, src/client/openai_compatible.rs, src/client/perplexity.rs, src/client/qianwen.rs, src/client/replicate.rs, src/client/vertexai.rs, src/config/mod.rs
openai-compatible platforms like groq/perplexity/mistral share the same `openai-compatible` client.
````diff
--  - type: mistral
++  - type: openai
++    name: mistral
api_key: xxx                                      # ENV: {client_name}_API_KEY
```
=> feat: openai-compatible platforms share the same client

Argcfile.sh, src/client/bedrock.rs, src/client/qianwen.rs, src/config/session.rs, src/render/markdown.rs, src/utils/tiktoken.rs
I fixed some typos.
If you want to detect typos on CI. I can make PR.
If you want to detect typos in your local machine, please try following instruction:
1. Install https://github.com/crate-ci/typos#install
2. Add config file named `_typos.toml` like following to root of this repository:
```toml
[files]
extend-exclude = ["assets/*"]
```
3. Run `typos`
4. Then, if there are some typos, output is like this:
=> chore: fix typos

assets/arena.html, assets/playground.html, src/client/model.rs, src/config/mod.rs, src/serve.rs
```
$ aichat --serve
Chat Completions API: http://0.0.0.0:8000/v1/chat/completions
LLM Playground:       http://0.0.0.0:8000/playground
LLM ARENA:            http://0.0.0.0:8000/arena
```
=> feat: support playground/arena webui

assets/arena.html, assets/playground.html
- when shift-enter input newline in textarea, preserve insert position
- support dark color-scheme
=> refactor: improve webui

src/client/common.rs, src/config/input.rs, src/config/mod.rs, src/config/role.rs, src/main.rs, src/repl/mod.rs, src/serve.rs
```
- name: emoji
prompt: >
I want you to translate the sentences I write into emojis.
I will write the sentence, and you will express it with emojis.
I just want you to express it with emojis. I don't want you to reply with anything but emoji.
The sentence to be translated: __INPUT__
model: openai:gpt-3.5-turbo  # <- support binding model to the role
```
close #502
=> feat: allow binding model to the role

src/config/mod.rs
=> fix: no builtin roles if no roles.yaml

src/main.rs
=> refactor: non-zero exit code when model call fails

assets/arena.html, assets/playground.html
=> feat: webui add toolbox(copy-bt/regenerate-btn) to message

assets/arena.html, assets/playground.html
=> refactor: webui limit height of input textarea

src/function.rs
LLM_FUNCTION_DATA contains parameters in a JSON string, which is useful for passing arguments to JavaScript, Python, and Ruby functions.
=> refactor: export LLM_FUNCTION_DATA when calling functions

assets/arena.html, assets/playground.html
The web UI doesn't have to be used within AIChat. It can be copied and used elsewhere.
=> feat: webui operates independently from aichat

src/function.rs
AIChat pass JSON data directly as first positional argument to function tools
```
may_execute_command '{"command":"echo \"hello world\""}' 
```
=> refactor: no export LLM_FUNCTION_DATA, pass json as command arg

src/function.rs, src/utils/mod.rs
Instead of Yes/no, We have three choices now.
=> refactor: change prompt for executing tool functions

Cargo.lock, Cargo.toml, README.md, config.example.yaml
https://github.com/sigoden/aichat/blob/chore-release/README.md
=> chore: release v0.18.0

src/config/mod.rs
| ENV-VAR              | INFO-KEY      | DEFAULT-VALUE                          |
| -------------------- | ------------- | -------------------------------------- |
| AICHAT_CONFIG_FILE   | config_file   | `<user-config-dir>/aichat/config.yaml` |
| AICHAT_ROLES_FILE    | roles_file    | `<user-config-dir>/aichat/roles.yaml`  |
| AICHAT_MESSAGES_FILE | messages_file | `<user-config-dir>/aichat/messages.md` |
| AICHAT_SESSIONS_DIR  | sessions_dir  | `<user-config-dir>/aichat/sessions`    |
| AICHAT_RAGS_DIR      | rags_dir      | `<user-config-dir>/aichat/rags`        |
| AICHAT_FUNCTIONS_DIR | functions_dir | `<user-config-dir>/aichat/functions`   |
=> feat: custom more path to file/dirs with environment variables

src/client/vertexai.rs
Found that the quality of some chats has declined.
=> revert: feat: use systemInstruction for gemini-1.5-* models (#564)

src/config/input.rs
=> refactor: change error message of the model does not support vision

src/function.rs
=> fix: infinite loop of function calls on poor LLM

Cargo.lock, Cargo.toml, src/rag/loader.rs, src/rag/mod.rs
- Use pdftotext to load pdf file
- Use pandoc load docx file
=> refactor: load pdf/docx files

src/config/bot.rs, src/config/input.rs, src/config/mod.rs, src/repl/mod.rs
=> feat: add `.starter` repl command

scripts/completions/aichat.bash, scripts/completions/aichat.fish, scripts/completions/aichat.nu, scripts/completions/aichat.ps1, scripts/completions/aichat.zsh, src/cli.rs, src/config/bot.rs, src/config/mod.rs, src/config/session.rs, src/main.rs, src/rag/mod.rs, src/repl/mod.rs, src/utils/abort_signal.rs
```
-b, --bot <BOT>            Start a bot
--rag <RAG>            Start a RAG
--list-bots            List all bots
--list-rags            List all RAGs
```
=> feat: add rag and bot related cli options

src/client/cohere.rs
cohere cannot specify both message and tool_results in multistep mode
=> fix: cohere tool use

Cargo.lock, Cargo.toml, README.md, config.example.yaml, src/config/input.rs, src/config/mod.rs, src/rag/bm25.rs, src/rag/mod.rs, src/utils/spinner.rs
- hnsw for vector search
- bm25 for full-text search
- rrf for combining the search results
=> feat: rag hybrid search

assets/arena.html, assets/playground.html, config.example.yaml, models.yaml, src/client/common.rs, src/client/model.rs
```diff
-     mode: embedding
+     type: embedding
max_input_tokens: 8191
default_chunk_size: 3000
max_concurrent_chunks: 100
```
=> refactor: rename model.mode to model.type

config.example.yaml, src/config/session.rs, src/repl/mod.rs
1. no require compress_threshold >= 1000
2. no compressing in middle of function calling
=> refactor: compress session

src/config/mod.rs, src/rag/loader.rs, src/rag/mod.rs, src/repl/mod.rs, src/utils/request.rs, src/utils/spinner.rs
If you think the documents have changed, you can update the RAG using `.rebuild rag`.
=> feat: support `.rebuild rag`

config.example.yaml, src/config/agent.rs, src/config/mod.rs, src/config/role.rs, src/config/session.rs, src/function.rs
=> feat: enhenced flexibility for use tools

config.example.yaml, src/config/agent.rs, src/config/mod.rs, src/function.rs
=> feat: agent can reuse tools

src/config/input.rs, src/rag/loader.rs, src/utils/mod.rs, src/utils/path.rs
```
aichat --file path-to-dir1 --file path-to-dir2/**/*.md
.file path-to-dir1/ path-to-dir2/**/*.md
```
=> feat: `--file/.file` can load dirs

src/client/common.rs, src/utils/mod.rs
Use a new algorithm to estimate token length.
=> refactor: improve estimate_token_length

src/config/input.rs
```
TEXT
`PATH1`:
CONTENT
`PATH2`:
CONTENT
...
```
=> refactor: template of including files

assets/arena.html, assets/playground.html
=> fix: webui input-panel exceeds viewpoint on mobile

src/client/common.rs, src/client/ernie.rs, src/utils/mod.rs
=> refactor: config creation prompt aware of env var

src/config/input.rs
Fix for problem with token limit applied from default model instead of selected model.
See #734.
=> fix: problem with input token limit

Argcfile.sh, src/client/ollama.rs
> NOTE: Streaming tool use is not yet supported.
=> feat: ollama support tools and new embeddings api

src/client/common.rs
```
AICHAT_COHERE_PATCHES='{".*":{"chat_completions_body":{"connectors":[{"id":"web-search"}]}}}'  \
aichat -m cohere:command what is the latest version of node.js
```
=> feat: set model patches with `AICHAT_{client}_PATCHES`

config.example.yaml, src/client/azure_openai.rs, src/client/bedrock.rs, src/client/claude.rs, src/client/cloudflare.rs, src/client/cohere.rs, src/client/common.rs, src/client/ernie.rs, src/client/gemini.rs, src/client/macros.rs, src/client/ollama.rs, src/client/openai.rs, src/client/openai_compatible.rs, src/client/qianwen.rs, src/client/rag_dedicated.rs, src/client/replicate.rs, src/client/vertexai.rs
```diff
-     patches: 
-       <regex>:                                      # The regex to match model names, e.g. '.*' 'gpt-4o' 'gpt-4o|gpt-4-.*'
-         chat_completions_body:                      # The JSON to be merged with the chat completions request body.
-           <json>
+     patch:                                          # Patch api request
+       chat_completions_body:                        
+         <regex>:                                    # The regex to match model names, e.g. '.*' 'gpt-4o' 'gpt-4o|gpt-4-.*'
+           <json>                                    # The JSON to be merged with the chat completions request body.
```
=> feat: change model patch structure

models.yaml, src/client/bedrock.rs
- switch chat completions api from Invoke/InvokeModelWithResponseStream to Converse/ConverseStream
- support mistral large v2
- support cohere models
=> feat: bedrock client switch to converse api and support cohere models

src/config/agent.rs, src/rag/mod.rs, src/utils/mod.rs
=> feat: ask for confirmation when some rag documents fail to load

src/config/mod.rs, src/main.rs
=> refactor: do not abandon AICHAT_PLATFORM

config.example.yaml, src/config/mod.rs, src/repl/mod.rs
```diff
- buffer_editor: null
+ editor: null
```
=> feat: rename `config.buffer_editor` to `config.editor`

src/client/claude.rs
=> fix: claude fails to run tools with zero arguments

src/client/model.rs, src/config/input.rs, src/config/mod.rs
```
> .role %functions% what is the weather in London?
WARNING: This LLM or client does not support function calling, despite the context requiring it.
```
=> feat: no check model's support for function calls

assets/arena.html, assets/playground.html
=> refactor: webui render error

Argcfile.sh, config.example.yaml, models.yaml, src/client/mod.rs, src/client/openai.rs
```yaml
name: ai12
api_key: xxx
```
=> feat: support ai21 client

src/config/mod.rs, src/config/role.rs, src/config/session.rs, src/main.rs, src/repl/mod.rs, src/serve.rs
=> feat: replace roles.yaml with roles/<name>.md

src/config/agent.rs, src/config/mod.rs, src/config/session.rs
=> feat: save temp session with `temp-<timestamp>` if `save_session: true`

assets/playground.html, src/config/input.rs, src/config/mod.rs, src/main.rs, src/serve.rs
=> feat: webui support RAG

src/config/mod.rs, src/repl/mod.rs
```
.delete                  Delete roles/sessions/RAGs/agents-config
```
https://github.com/user-attachments/assets/cc4cd55f-f24e-409b-9c79-f13694a88a2c
=> feat: add `.delete` repl command

src/config/mod.rs, src/main.rs
=> refactor: role/session/agent should not inherit the global `use_tools`

src/config/mod.rs, src/rag/mod.rs, src/repl/mod.rs
=> feat: add `.source rag` repl command

Cargo.lock, Cargo.toml, README.md
https://github.com/sigoden/aichat/releases/tag/v0.22.0-rc3
=> chore: release v0.22.0

src/rag/mod.rs
Benifits: Even if the embedding model is removed from models.yaml, the RAG will still work.
=> feat: add batch_size to rag yaml

src/config/mod.rs, src/repl/mod.rs
=> refactor: several improvement

src/rag/mod.rs
Users can set environment variable `AICHAT_EMBEDDINGS_RETRY_LIMIT` to control embeddings retry limits.
The retry delay will be 1 second, 2 seconds, 4 seconds, etc., with the highest number of retries (in seconds) being 2.
relate to #877
=> feat: add AICHAT_EMBEDDINGS_RETRY_LIMIT

src/config/mod.rs
=> feat: respect XDG_CONFIG_HOME for placing config dir

src/main.rs, src/utils/mod.rs
=> feat: change prompt for choosing shell actions

src/main.rs
=> fix: unexpected REPL without tty

src/config/mod.rs, src/config/session.rs
After this PR is merged, when we reload the session or clear the messages, the role will still be synced.
=> feat: session persists role name

assets/arena.html, assets/playground.html
=> feat: webui supports pasting images

src/main.rs, src/repl/mod.rs, src/utils/clipboard.rs
=> feat: add shell action `copy`

Cargo.lock, Cargo.toml, src/rag/mod.rs
Drop language detection to minimize binary size.
=> refactor: rag bm25

src/config/agent.rs, src/config/mod.rs, src/config/role.rs, src/config/session.rs, src/main.rs, src/rag/mod.rs, src/repl/mod.rs, src/utils/mod.rs
- rename agents_config_dir to agents_data_dir
- do not save empty role name while saving the session
- rename delete keys (roles/sessions/rags/agents => role/session/rag/agent-data)
- improve some printing messages
=> refactor: several improvements

Cargo.lock, Cargo.toml, README.md
https://github.com/sigoden/aichat/releases/tag/v0.23.0-rc1
=> chore: release v0.23.0

src/client/common.rs, src/main.rs, src/repl/mod.rs, src/utils/spinner.rs
=> fix: unexpected Ctrl-C/Ctrl-D handling in non-stream REPL Chat

src/config/mod.rs, src/config/session.rs
=> feat: `.info role`/`.exit role` works for session role

src/config/agent.rs, src/rag/mod.rs
=> refactor: users can choose whether to initialize the agent RAG

src/config/agent.rs, src/config/mod.rs, src/config/session.rs, src/function.rs, src/repl/mod.rs
Different sessions can have different agent variables.
=> feat: support session-scoped agent variables

src/rag/mod.rs
=> refactor: `.sources rag` show document ids

Argcfile.sh, config.example.yaml, models.yaml, src/client/mod.rs
```yaml
name: hunyuan
api_base: https://api.hunyuan.cloud.tencent.com/v1
api_key: xxx
```
=> feat: add hunyuan client

src/serve.rs
=> fix: WebUI unsupported value error when invoking o1-* models

src/config/mod.rs
For example:
```
DEMO_CONFIG_FILE=tmp/config.yaml   aichat --agent demo --info
```
=> feat: support env `<AGENT_NAME>_CONFIG_FILE`

Argcfile.sh, src/client/bedrock.rs, src/client/claude.rs, src/client/cohere.rs, src/client/ernie.rs, src/client/openai.rs, src/client/vertexai.rs, src/config/input.rs, src/function.rs, src/serve.rs
```
$ aichat -S -m qianwen:qwen-turbo-latest -r %functions% what is the weather in Pairs and Berlin?
Call get_current_weather {"location":"Paris"}
Call get_current_weather {"location":"Berlin"}
Error: Failed to call chat-completions api
Caused by:
<400> InternalError.Algo.InvalidParameter: messages with role "tool" must be a response to a preceeding message with "tool_calls". (type: invalid_request_error)
```
=> fix: invalid request on qianwen multi tool-calls

src/client/bedrock.rs, src/client/claude.rs, src/client/cohere.rs, src/client/ernie.rs, src/client/message.rs, src/client/mod.rs, src/client/model.rs, src/client/openai.rs, src/client/vertexai.rs, src/config/input.rs, src/config/mod.rs, src/config/session.rs, src/function.rs, src/main.rs, src/repl/mod.rs, src/serve.rs
- rename MessageContent:ToolResults to MessageContent:ToolCalls
- rename ToolResults to MessageContentToolCalls
- persist tool_calls to messages.md
=> refactor: improve tool calls

Cargo.lock, Cargo.toml, README.md
https://github.com/sigoden/aichat/releases/tag/v0.24.0-rc3
=> chore: release v0.24.0

src/config/input.rs, src/main.rs, src/rag/mod.rs, src/render/stream.rs, src/repl/mod.rs, src/utils/spinner.rs
=> feat: handle Ctrl+C during every spinner in REPL

src/client/bedrock.rs, src/client/claude.rs, src/client/ernie.rs, src/client/openai.rs
Fix stream function calling for oai/ollama/siliconflow/hunyuan
=> fix: stream function calling for openai-compatible client

assets/arena.html, assets/playground.html
The playground can save the session in memory for reuse.
https://github.com/user-attachments/assets/bc91a288-d285-491c-b0ed-e3166d2b013d
**Why not saved to localstorage?**
LocalStorage has limited capacity, If the session messages are a bit longer or include some images, there may not be enough space to store multiple sessions. On the contrary, there is indeed enough memory available.
=> feat: webui playground support multiple sessions in memory

assets/arena.html, assets/playground.html
=> feat: webui supports math in markdown

Argcfile.sh, config.example.yaml, models.yaml, src/client/cohere.rs
see https://docs.cohere.com/docs/migrating-v1-to-v2
=> feat: update cohere api to v2

config.example.yaml, src/config/mod.rs, src/main.rs
append_command_to_history_file => save_shell_history
Affect #1026
=> refactor: change config field name

models.yaml, src/client/vertexai.rs
=> feat: support gemini-2.0-flash-thinking-exp

Cargo.lock, Cargo.toml
https://github.com/sigoden/aichat/releases/tag/v0.26.0
=> chore: release v0.26.0

scripts/completions/aichat.bash, scripts/completions/aichat.fish, scripts/completions/aichat.nu, scripts/completions/aichat.ps1, scripts/completions/aichat.zsh, src/cli.rs, src/main.rs
```
aichat --rag aichat-wiki --rebuild-rag
aichat --rag aichat-wiki --rebuild-rag Where is the config path
```
close #1073  #1061
=> feat: add cli option `--rebuild-rag`

src/config/input.rs, src/config/mod.rs, src/repl/mod.rs
```
.file %% -- translate to <lang>
```
=> feat: `.file` supports including last reply with `%%`

src/config/mod.rs, src/main.rs, src/repl/mod.rs
```
.agent
Usage: .agent <agent-name> [session-name|null] [key=value]...
```
```
.agent demo null username=alice
```
=> feat: `.agent` accept variable key-value pairs

src/config/mod.rs, src/repl/mod.rs
```
.starter <number>
.starter 1
```
=> feat: `.starter` accepts index other than text

src/config/mod.rs, src/repl/mod.rs
- autocomplete variables
- optional session name
```
.agent demo
.agent demo test1
.agent demo username=alice
```
Relate to #1090
=> refactor: improve `.agent` repl command

src/config/mod.rs, src/main.rs
If the model is misconfigured, running `aichat --info` or `aichat --list-models` still throws an `Unknown model ...` error. 
This is not helpful for troubleshooting; aichat should display information and models instead.
=> refactor: don't throw model/functions related error in info mode

src/config/mod.rs, src/config/session.rs, src/repl/mod.rs
```
.edit config             Edit the configuration file
.edit agent-config       Edit the agent-specific config file
```
=> feat: support `.edit config` and `.edit agent-config` repl commands

src/config/agent.rs, src/config/mod.rs
If a variable has a default value, include it in the related completion description.
=> refactor: improve autocompletion for agent variable

Cargo.lock, Cargo.toml, src/config/mod.rs, src/repl/completer.rs, src/utils/mod.rs
=> refactor: sort repl autocompletion items by fuzzy-match score

src/config/mod.rs
=> refactor: save model-override file as yaml

Argcfile.sh, config.example.yaml, models.yaml, src/client/mod.rs
```
name: novita
api_base: https://api.novita.ai/v3/openai
api_key: xxx
```
=> feat: add novita client

src/client/openai.rs
- deepseek reasoning_content
- openrouter reasoning
=> feat: display reasoning tokens

src/config/mod.rs
=> fix: messages with tool_calls have not been saved to messages.md

src/repl/mod.rs
Relate to https://github.com/sigoden/aichat/issues/687#issuecomment-2643645249
=> refactor: change extension of ctrl+o opened file to `.md`

src/client/common.rs, src/client/macros.rs
During configuration initialization, we previously automatically selected the first model from the provider's model list, now we support selecting LLM.
=> feat: supports selecting LLM during configuration initialization

Cargo.lock, Cargo.toml, README.md
https://github.com/sigoden/aichat/releases/tag/v0.28.0-rc3
=> chore: release v0.28.0

models.yaml, src/client/bedrock.rs, src/client/claude.rs, src/client/openai.rs
Document: https://docs.anthropic.com/en/docs/build-with-claude/extended-thinking.
NOTE: AIChat currently does not support claude extended thinking with tool use.
=> feat: support claude-3-7

src/client/azure_openai.rs
Need for O1/O3 model support with `-f`.
Awesome work with aichat I love it. If I have some bandwidth I could work on making this configurable. Would you be interested in it?
=> Bumping Azure OpenAI API Version to 2024-12-01-preview

src/utils/path.rs
Newly accepted glob patterns:
```
*.md
dir/*.md
**/*.md
```
Close #1204
=> feat: enhence glob for `--file` and rag docs

Cargo.lock, Cargo.toml
https://github.com/sigoden/aichat/releases/tag/v0.29.0-rc1
=> chore: release v0.29.0

Argcfile.sh, config.example.yaml, models.yaml, src/client/mod.rs
01.AI hasn't released a new model in a while.
=> feat: abandon support for lingyiwanwu client

Cargo.lock, Cargo.toml, README.md
https://github.com/sigoden/aichat/releases/tag/v0.30.0-rc1
=> chore: release v0.30.0

src/client/vertexai.rs
=> fix: use proper endpoint for vertexai "global" location

src/config/session.rs
=> feat: cache session token counts to avoid typing delay

src/render/mod.rs, src/render/stream.rs
Relate to https://github.com/sigoden/aichat/pull/1366#issuecomment-3143691872
=> feat: switch to raw stream renderer when no_color/no_highlight
